apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-fun
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
    spec:
      containers:
        - image: hello-fun
          livenessProbe:
            httpGet:
              path: /actuator/info
          readinessProbe:
            httpGet:
              path: /actuator/health
