apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: hello-fun
build:
  artifacts:
  - image: hello-fun
    jib:
      project: com.example:hello-fun
manifests:
  rawYaml:
  - knative/service.yaml
resourceSelector:
  allow:
    - groupKind: "Service.serving.knative.dev"
      image: [".*"]
      labels: [".*"]
